events {}

http {
  upstream backend {
    # Initial setup: only v1
    server backend:3000;

    # Uncomment below to simulate rolling update with v2
    # server backend-v2:3000;
  }

  server {
    listen 80;

    location /api/ {
      proxy_pass http://backend;
    }

    location / {
      proxy_pass http://frontend:80;
    }
  }
}
